name: Publish Android Library

on:
  push:
    branches: '**/**'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build and publish library
        run: |
          ./gradlew clean build
          ./gradlew publishToMavenLocal

      - name: Publish to GitHub Packages
        run: |
          echo "//maven.pkg.github.com/PivotMasterApps/premium/:username=pivotmasterapps" > ~/.gradle/gradle.properties
          echo "//maven.pkg.github.com/PivotMasterApps/premium/:password=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" >> ~/.gradle/gradle.properties
          ./gradlew publish
        env:
          USERNAME_GITHUB: ${{ secrets.USERNAME_GITHUB }}
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
