name: Publish Android Library

on:
  push:
    branches: '**/**'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build and publish library
        run: |
          ./gradlew clean build -PgithubUsername=${{ secrets.USERNAME_GITHUB }} -PgithubToken=${{ secrets.TOKEN_GITHUB }}
          ./gradlew publishToMavenLocal

      - name: Publish to GitHub Packages
        run: |
          echo "//maven.pkg.github.com/PivotMasterApps/premium/:username=\${{ secrets.USERNAME_GITHUB }}" >> $GITHUB_ENV
          echo "//maven.pkg.github.com/PivotMasterApps/premium/:password=\${{ secrets.TOKEN_GITHUB }}" >> $GITHUB_ENV
          ./gradlew publish
        env:
          GITHUB_USERNAME: ${{ secrets.USERNAME_GITHUB }}
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}