name: Publish Android Library

on:
  push:
    branches: '**/**'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build and publish library
        run: |
          ./gradlew clean build

      - name: Debug Gradle Properties
        run: cat ~/.gradle/gradle.properties

      - name: Publish to GitHub Packages
        run: |
          echo "//maven.pkg.github.com/PivotMasterApps/premium/:username=${{ secrets.USERNAME_GITHUB }}" > ~/.gradle/gradle.properties
          echo "//maven.pkg.github.com/PivotMasterApps/premium/:password=${{ secrets.TOKEN_GITHUB }}" >> ~/.gradle/gradle.properties
          ./gradlew publish
        env:
          USERNAME_GITHUB: ${{ secrets.USERNAME_GITHUB }}
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
